#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.js' '*.jsx' '*.ts' '*.tsx' '*.json' '*.css' '*.scss' '*.html' '*.md')

if [ -n "$STAGED_FILES" ]; then
  echo "Running lint and format on staged files..."
  echo "$STAGED_FILES" | xargs yarn lint
  echo "$STAGED_FILES" | xargs yarn format
  git add $STAGED_FILES
else
  echo "No staged files to lint or format."
fi